"""empty message

Revision ID: dcc9f8da18dc
Revises: 
Create Date: 2021-05-31 21:26:22.056758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc9f8da18dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('House',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neighbourhood_group', sa.String(), nullable=False),
    sa.Column('neighbourhood', sa.String(), nullable=False),
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('minimum_nights', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('House')
    # ### end Alembic commands ###
